const designs=[
 ['Precision','Dense / Inline','A compact spectrum-first list. Crisp selection outlines and controls revealed on hover.'],
 ['Soft tiles','Inset / Rounded','Separate, softly rounded entries with quieter hierarchy and persistent palette actions.'],
 ['Register','Columns / Aligned','A structured name-and-spectrum register. Alternating rows make long lists easier to scan.'],
 ['Colour shelf','Spectrum / Generous','Taller colour ribbons lead each entry, with names underneath and actions alongside.'],
 ['Quiet list','Open / Minimal','An airy, borderless list. A small tick marks selection while the colours do the work.'],
 ['Capsule','Compact / Contained','Rounded entries group the name and spectrum; small count badges finish each row.'],
 ['Outlined','Bounded / Precise','Fine outlines define every entry, with separated colour segments and a clear active state.'],
 ['Indexed','Numbered / Detailed','Catalogue-style numbering and visible colour metadata support deliberate comparison.'],
 ['Inspector','Content / Actions','A dedicated action gutter separates favourites and pick targets from palette content.'],
 ['Floating focus','Spacious / Layered','Detached colour chips and a raised active row give the selected palette a clear focus.']
];
const source=[
 [145,['F4666D','F18479','D2A09B','9DA1AC','7695A7']],
 [144,['D74650','E67468','FF9E74','F3C3A6','FFEBD0']],
 [143,['FAFFF0','D2DCBC','94AB9F','3B5D6B','16313D']],
 [140,['2A1720','5D414B','F1E8D2','23465B']],
 [138,['428E90','7EC7CD','FFF0CD','FFC7BF']],
 [137,['952003','E44B06','FFA518','087D85','3CBFB9']],
 [136,['16BBA0','17566D','F04B6B','ACAFB3','FFFFFF']],
 [135,['FFFFFF','27B69E','FF444A','3A4149','20282D']],
 [134,['123441','1E617B','E7E3BD','FFAB16','FF7A05']],
 [133,['E6E8D1','CCCDA6','FFFFF6','28333A','A30A2E']],
 [132,['FF405B','F79AAA','B6E7DA','00A58E','EAE9CB']],
 [131,['27013E','81064B','D35911','FFAA05']],
 [130,['36465A','839B9D','F8F8EE','F13E37']],
 [129,['385D71','FE844D','FFBD78','75AE95','F1F8CD']],
 [128,['F3EBD2','C3D7D1','7DB1B2','3F8090','153449']],
 [127,['AAEBE9','009C9D','F44A73','FFFFFF','C4C6C9']],
 [126,['CE3F51','FF6D70','FFAD6D','FFE3A3','9DBAFF']],
 [125,['172F35','7CBEBA','FF0060','242D34','3B5661']],
 [124,['3AB996','F9D465','F1A245','E96347']],
 [123,['A72948','F0DFC0','AA8990','CAAF9D','664A45']],
 [122,['185B70','149B8F','66CEA4','FFBC38','FF5B47']],
 [121,['2A3B4B','3B6975','AFD8DE','FFFFFF','CE1932']],
 [120,['FFF0A3','94C9A2','FF574A','074B50','E9908C']],
 [119,['59536C','B0E1D0','F5F5DE','899DAD','DE6358']],
 [112,['B01874','F03A88','B4D82D','00B8A9','FFD231','F46D29','F349A2','A973D2','2DAFEA','087CA4']],
 [111,['96B5FF','162C6C','EEFA53','087B6B','F9FFEC','FFFFFF','E3EBED']],
 [108,['F75167','7ADAAD','2AAB9C','F3DB51','FF7127','7946A1','20B5DA','233E6A','EA7A94','B8CF73','7D9EBC','193535','FBA327','AA252F','00A578','E6DBB5','C3BBDD','D86687','FCF9DB','8C9894','292F41','FCB653','FFFFFF','16191D']]
];
const palettes=source.map(([id,hexes])=>({id,name:`Palette ${id}`,colours:hexes.map(h=>'#'+h)}));
let current=0,theme='light',selected=145,target=145,favourites=new Set([145,143,138]),open=new Set(['clients','mmffdev','products','colorgain','web','library-palettes']),activeTree='web-palettes',queries={light:'',dark:''},onlyFav={light:false,dark:false};
const icons={chevron:'<path d="m4 6 4 4 4-4"/>',folder:'<path d="M2 5V3h5l2 2h5v8H2Z"/><path d="M2 7h12"/>',building:'<path d="M4 14V2h8v12M2 14h12M7 14v-3h2v3M6 5h.1M10 5h.1M6 8h.1M10 8h.1"/>',palette:'<path d="M3 2h6v12H3zM9 4l4 2-4 7M6 5h0M6 8h0M6 11h0"/>',info:'<circle cx="8" cy="8" r="6"/><path d="M8 7v4M8 4.5h.01"/>',type:'<path d="m1 12 4-9 4 9M3 8h4M14 12V7h-3v5h3"/>',tag:'<path d="M2 2h5l7 7-5 5-7-7Z"/><circle cx="5" cy="5" r=".6"/>',stream:'<rect x="2.5" y="2.5" width="11" height="11" rx="1" stroke-dasharray="2 2"/>',star:'<path d="m8 1 2.1 4.4 4.9.7-3.5 3.5.8 4.9L8 12.2l-4.3 2.3.8-4.9L1 6.1l4.9-.7Z"/>',target:'<circle cx="8" cy="8" r="6"/><circle cx="8" cy="8" r="2"/>',search:'<circle cx="6.5" cy="6.5" r="4.5"/><path d="m10 10 4 4"/>',sliders:'<path d="M2 4h12M2 8h12M2 12h12"/><circle cx="5" cy="4" r="1.5"/><circle cx="11" cy="8" r="1.5"/><circle cx="6" cy="12" r="1.5"/>',pipette:'<path d="m3 11 7-7 2 2-7 7H3ZM9 3l4 4M11 2l3 3M2 14l1-1"/>'};
function icon(name){return `<span class="icon" aria-hidden="true"><svg viewBox="0 0 16 16">${icons[name]||icons.folder}</svg></span>`}
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function spectrum(p){return `<span class="spectrum" role="img" aria-label="${p.colours.length} colours: ${p.colours.join(', ')}">${p.colours.map(c=>`<i style="background:${c}"></i>`).join('')}</span>`}
function row(p,index,mini=false){return `<div class="palette-row ${selected===p.id?'selected':''}" data-palette="${p.id}"><span class="row-number">${String(index+1).padStart(2,'0')}</span><button class="palette-hit" data-action="select" data-id="${p.id}" aria-pressed="${selected===p.id}" aria-label="Select ${p.name}"><span class="palette-name">${p.name}</span><span class="palette-meta">${spectrum(p)}</span><span class="row-note">${p.colours.length} colours${target===p.id?' · Pick target':''}</span></button><div class="palette-tools"><button class="tool star ${favourites.has(p.id)?'on':''}" data-action="favourite" data-id="${p.id}" aria-label="Favourite ${p.name}" aria-pressed="${favourites.has(p.id)}">${icon('star')}</button><button class="tool target ${target===p.id?'on':''}" data-action="target" data-id="${p.id}" aria-label="Use ${p.name} as pick target" aria-pressed="${target===p.id}">${icon('target')}</button><span class="count">${p.colours.length}</span></div></div>`}
const tree=[
 {id:'clients',name:'Clients',icon:'folder',children:[{id:'mmffdev',name:'MMFFDev',icon:'building',count:1,children:[{id:'products',name:'Products',icon:'building',count:1,children:[{id:'colorgain',name:'Colorgain',icon:'folder',count:0,children:['Web','Print','Design'].map(name=>({id:name.toLowerCase(),name,icon:'stream',children:[{id:name.toLowerCase()+'-information',name:'Information',icon:'info'},{id:name.toLowerCase()+'-palettes',name:'Palettes',icon:'palette'},{id:name.toLowerCase()+'-typography',name:'Typography',icon:'type'},{id:name.toLowerCase()+'-tags',name:'Tags',icon:'tag',children:[{id:name.toLowerCase()+'-edit-tags',name:'Edit Tags',icon:'sliders'}]}]}))}]}]}]},
 {id:'my-products',name:'My Products',icon:'folder',children:[{id:'own-products',name:'Products',icon:'building',count:1,children:[{id:'vector',name:'Vector',icon:'folder',count:0,children:[{id:'vector-information',name:'Information',icon:'info'},{id:'vector-palettes',name:'Palettes',icon:'palette'},{id:'vector-typography',name:'Typography',icon:'type'},{id:'vector-tags',name:'Tags',icon:'tag'}]}]}]}
];
function treeHTML(nodes,depth=0){return nodes.map(n=>`<div class="tree-row ${activeTree===n.id?'selected':''}" style="--depth:${depth}"><button class="tree-main" data-action="${n.children?'folder':'tree'}" data-node="${n.id}" ${n.children?`aria-expanded="${open.has(n.id)}"`:''}><span class="chev ${open.has(n.id)?'':'closed'}">${n.children?'<svg viewBox="0 0 16 16">'+icons.chevron+'</svg>':''}</span>${depth?icon(n.icon):''}<span class="text">${n.name}</span></button>${n.count!==undefined?`<span class="count">${n.count}</span>`:''}</div>${n.children&&open.has(n.id)?treeHTML(n.children,depth+1):''}`).join('')}
function header(title,left,right,arrow){return `<header class="rail-head"><div class="heading-line"><h3>${title}</h3>${arrow?'<button data-action="collapse" aria-label="Collapse Library">↙</button>':''}</div><div class="column-labels"><span>${left}</span><span>${right}</span></div></header>`}
function chrome(){return `<div class="app-chrome" aria-label="Existing app header, unchanged"><div class="brand-area"><strong>colorgain</strong><span class="app-tools">${icon('pipette')}${icon('stream')}</span></div><div class="app-nav"><span class="current">Library</span><span>Palettes</span><span>Lab</span><span>Contrast</span><span>Projects</span></div></div>`}
function pair(d,t,mini=false){const list=mini?palettes.slice(0,12):palettes;return `<div class="rail-pair v${d+1} ${t}" data-appearance="${t}" data-design="${d}">${chrome()}<div class="rails"><section class="rail library" aria-label="Rail 1: Library">${header('Library','Name','Count',true)}<div class="rail-content">${treeHTML(tree)}<div class="section-title"><button data-action="folder" data-node="library-palettes" aria-expanded="${open.has('library-palettes')}"><span class="chev ${open.has('library-palettes')?'':'closed'}"><svg viewBox="0 0 16 16">${icons.chevron}</svg></span>Palettes<span class="count">${palettes.length}</span></button></div><div class="palette-list library-list">${open.has('library-palettes')?list.map((p,i)=>row(p,i,mini)).join(''):''}</div></div></section><section class="rail palette-rail" aria-label="Rail 2: Palettes">${header('Palettes','Palette','Colours',false)}<div class="rail-content"><div class="list-toolbar"><label class="search">${icon('search')}<input type="search" placeholder="Find a palette" aria-label="Find a palette in ${t} view" value="${mini?'':esc(queries[t])}"></label><button class="filter" data-action="filter" aria-pressed="${mini?false:onlyFav[t]}">Favourites</button></div><div class="palette-list results">${list.filter(p=>mini||matches(p,t)).map((p,i)=>row(p,i,mini)).join('')||'<p class="empty">No matching palettes.</p>'}</div></div></section></div></div>`}
function matches(p,t){return p.name.toLowerCase().includes(queries[t].toLowerCase())&&(!onlyFav[t]||favourites.has(p.id))}
function updateSelection(){const p=palettes.find(p=>p.id===selected),t=palettes.find(p=>p.id===target);document.getElementById('selection').innerHTML=`<strong>${p.name}</strong><span class="selection-swatches">${p.colours.map(c=>`<span class="colour-chip" style="background:${c}" title="${c}"></span>`).join('')}</span><span class="selection-caption">${p.colours.length} Colours · Pick target: ${t.name} · ${favourites.size} Favourites</span>`}
function render(){document.getElementById('number').textContent=`Design ${String(current+1).padStart(2,'0')} / 10`;document.getElementById('title').textContent=designs[current][0];document.getElementById('description').textContent=designs[current][2];document.querySelectorAll('.choice').forEach((b,i)=>b.setAttribute('aria-pressed',i===current));document.querySelectorAll('[data-theme]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.theme===theme));document.getElementById('preview').innerHTML=(theme==='compare'?['light','dark']:[theme]).map(t=>`<div class="appearance">${theme==='compare'?`<p class="appearance-label">${t==='light'?'Light':'Dark'} · Rail 1 + Rail 2</p>`:''}<div class="preview-scroll">${pair(current,t)}</div></div>`).join('');updateSelection();history.replaceState(null,'',`#design-${current+1}-${theme}`)}
function refreshRows(){document.querySelectorAll('#preview .rail-pair').forEach(frame=>{const t=frame.dataset.appearance;frame.querySelectorAll('.palette-row').forEach(el=>{const p=palettes.find(p=>p.id===Number(el.dataset.palette));el.classList.toggle('selected',p.id===selected);el.querySelector('.palette-hit').setAttribute('aria-pressed',p.id===selected);const star=el.querySelector('.star'),pick=el.querySelector('.target');star.classList.toggle('on',favourites.has(p.id));star.setAttribute('aria-pressed',favourites.has(p.id));pick.classList.toggle('on',p.id===target);pick.setAttribute('aria-pressed',p.id===target);el.querySelector('.row-note').textContent=`${p.colours.length} colours${p.id===target?' · Pick target':''}`});if(onlyFav[t])refreshResults(frame)});updateSelection()}
function refreshResults(frame){const t=frame.dataset.appearance;frame.querySelector('.results').innerHTML=palettes.filter(p=>matches(p,t)).map((p,i)=>row(p,i)).join('')||'<p class="empty">No matching palettes.</p>'}
document.getElementById('designs').innerHTML=designs.map((d,i)=>`<button class="choice" data-design="${i}" aria-pressed="${i===0}"><span>${String(i+1).padStart(2,'0')}</span><strong>${d[0]}</strong><small>${d[1]}</small></button>`).join('');
document.getElementById('designs').onclick=e=>{const b=e.target.closest('[data-design]');if(b){current=Number(b.dataset.design);render()}};
document.querySelector('.theme-switch').onclick=e=>{const b=e.target.closest('[data-theme]');if(b){theme=b.dataset.theme;render()}};
document.getElementById('preview').onclick=e=>{const b=e.target.closest('[data-action]');if(!b)return;const frame=b.closest('.rail-pair'),action=b.dataset.action,id=Number(b.dataset.id);if(action==='select'){selected=id;refreshRows()}if(action==='favourite'){favourites.has(id)?favourites.delete(id):favourites.add(id);refreshRows()}if(action==='target'){target=id;refreshRows()}if(action==='filter'){const t=frame.dataset.appearance;onlyFav[t]=!onlyFav[t];b.setAttribute('aria-pressed',onlyFav[t]);refreshResults(frame)}if(action==='folder'){const node=b.dataset.node,appearance=frame.dataset.appearance;open.has(node)?open.delete(node):open.add(node);const saved=[...document.querySelectorAll('#preview .rail-content')].map(n=>n.scrollTop);render();document.querySelectorAll('#preview .rail-content').forEach((n,i)=>n.scrollTop=saved[i]||0);document.querySelector(`#preview .rail-pair[data-appearance="${appearance}"] [data-node="${node}"]`)?.focus({preventScroll:true})}if(action==='tree'){activeTree=b.dataset.node;document.querySelectorAll('#preview .tree-row').forEach(r=>r.classList.toggle('selected',r.querySelector('[data-node]')?.dataset.node===activeTree))}if(action==='collapse'){const rail=b.closest('.rail');rail.classList.toggle('collapsed');b.textContent=rail.classList.contains('collapsed')?'↗':'↙';b.setAttribute('aria-label',rail.classList.contains('collapsed')?'Expand Library':'Collapse Library')}};
document.getElementById('preview').oninput=e=>{if(e.target.matches('input[type=search]')){const frame=e.target.closest('.rail-pair');queries[frame.dataset.appearance]=e.target.value;refreshResults(frame)}};
document.getElementById('reset').onclick=()=>{selected=145;target=145;favourites=new Set([145,143,138]);open=new Set(['clients','mmffdev','products','colorgain','web','library-palettes']);activeTree='web-palettes';queries={light:'',dark:''};onlyFav={light:false,dark:false};render()};
document.getElementById('contact-sheet').innerHTML=designs.map((d,i)=>['light','dark'].map(t=>`<article class="thumbnail" data-design="${i}" data-theme-choice="${t}" aria-label="Open design ${i+1}, ${d[0]}, ${t}"><div class="thumb-window" aria-hidden="true" inert><div class="mini">${pair(i,t,true)}</div></div><button class="thumb-label"><strong>${String(i+1).padStart(2,'0')} ${d[0]}</strong><span>${t==='light'?'Light':'Dark'}</span></button></article>`).join('')).join('');
// Thumbnails are previews, not nested interactive controls.
document.querySelectorAll('.mini button,.mini input').forEach(el=>{el.disabled=true;el.tabIndex=-1});
document.getElementById('contact-sheet').onclick=e=>{const b=e.target.closest('.thumbnail');if(b){current=Number(b.dataset.design);theme=b.dataset.themeChoice;render();document.querySelector('.study-head').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'instant':'smooth',block:'start'})}};
const hash=location.hash.match(/^#design-(\d+)-(light|dark|compare)$/);if(hash){current=Math.max(0,Math.min(9,Number(hash[1])-1));theme=hash[2]}render();
// Fit each complete two-rail thumbnail to the available gallery width.
const thumbObserver=new ResizeObserver(entries=>entries.forEach(({target,contentRect})=>{const scale=contentRect.width/860;target.querySelector('.mini').style.transform=`scale(${scale})`;target.style.height=`${913*scale}px`}));document.querySelectorAll('.thumb-window').forEach(n=>thumbObserver.observe(n));
