const $=s=>document.querySelector(s), designs=[['Vector Spiral','The original 242 colours, with square swatches.','Spiral Spectrum'],['Colour Atlas','Every colour in one compact, hue-ordered field.','Colour Atlas'],['Tonal Columns','Compare lightness vertically and hue horizontally.','Hue & Tone'],['Spectrum Studio','Choose a hue, then tune saturation and brightness.','Spectrum & Shade'],['Hue Collections','Six colour families, each with its own tonal range.','Colour Families']];
const groups=[['Halo · Information',['Background','Text']],...['Primary','Secondary','Tertiary'].map(x=>['Halo · '+x+' Ring',['Background','Text','Cursor Background','Cursor Text']]),['Sidebar · Selection',['Background','Text']],['Buttons · Hover',['Background','Text']],['Buttons · Active',['Background','Text']]];
let settings=groups.flatMap(([group,names])=>names.map(name=>({group,name,value:name.includes('Text')?'#FFFFFF':'#393939',default:name.includes('Text')?'#FFFFFF':'#393939'})));
let saved={};try{saved=JSON.parse(localStorage.getItem('colorgain-picker-studies')||'{}')}catch{}settings.forEach((s,i)=>{if(/^#[0-9a-f]{6}$/i.test(saved[i]))s.value=saved[i]});
let selected=2,colour='#EF6548',design=0,theme='light',hue=10;let syncField=null;const all=wheelData.map(a=>a[3]);
function rgb(h){return [1,3,5].map(i=>parseInt(h.slice(i,i+2),16)/255)}
function hueOf(h){let [r,g,b]=rgb(h),max=Math.max(r,g,b),min=Math.min(r,g,b),d=max-min;if(!d)return 0;return ((max===r?(g-b)/d:max===g?(b-r)/d+2:(r-g)/d+4)*60+360)%360}
function hsl(h,s,l){s/=100;l/=100;let a=s*Math.min(l,1-l);return '#'+[0,8,4].map(n=>{let k=(n+h/30)%12;return Math.round(255*(l-a*Math.max(-1,Math.min(k-3,9-k,1)))).toString(16).padStart(2,'0')}).join('').toUpperCase()}
function button(c){let b=document.createElement('button');b.className='swatch';b.style.setProperty('--c',c);b.dataset.hex=c;b.setAttribute('aria-label','Choose '+c);b.title=c;b.onclick=()=>choose(c);return b}
function choose(c){colour=c.toUpperCase();document.documentElement.style.setProperty('--accent',colour);$('#preview').style.background=colour;$('#proposed').style.background=colour;$('#hex').value=colour;$('#error').textContent='';document.querySelectorAll('.swatch').forEach(b=>{b.classList.toggle('selected',b.dataset.hex===colour);b.setAttribute('aria-pressed',b.dataset.hex===colour)});context();if(syncField)syncField();$('#status').textContent=settings[selected].group+' · '+settings[selected].name+' → '+colour}
function sidebar(){let box=$('#targets');box.innerHTML='';let index=0;groups.forEach(([group,names])=>{let d=document.createElement('details');d.open=true;let sum=document.createElement('summary');sum.textContent=group;d.append(sum);names.forEach(name=>{let i=index++,s=settings[i],b=document.createElement('button');b.className='target'+(i===selected?' active':'');b.innerHTML=`<i style="background:${s.value}"></i><span>${name}</span>${s.value!==s.default?'<small>•</small>':''}`;b.onclick=()=>{selected=i;sidebar();context();choose(s.value)};d.append(b)});box.append(d)})}
function context(){let s=settings[selected];$('#target').textContent=s.group.replace(' · ',' / ')+' / '+s.name;$('#current').style.background=s.value;let isText=s.name.includes('Text');$('.mini').innerHTML=s.group.startsWith('Halo')?'<div class="miniring"><span>A</span><span>B</span><span>C</span></div>':'<div class="samplecontrol">'+(s.group.startsWith('Sidebar')?'Selected Palette':'Use Colour ↗')+'</div>';let sample=$('.miniring')||$('.samplecontrol');sample.style.color=isText?colour:'var(--ink)';if($('.miniring')){sample.style.borderColor=isText?'var(--rule)':colour;sample.style.background='var(--bg)'}else sample.style.background=isText?'var(--hover)':colour;let label=document.createElement('p');label.textContent=s.group+' · '+s.name;label.style.marginTop='12px';$('.mini').append(label)}
function hsv(c){let [r,g,b]=rgb(c),v=Math.max(r,g,b),m=Math.min(r,g,b);return [hueOf(c),v===0?0:(v-m)/v,v]}
function render(){syncField=null;let c=$('#canvas');c.innerHTML='';$('#designTitle').textContent=String(design+1).padStart(2,'0')+' / '+designs[design][0];$('#designNote').textContent=designs[design][1];$('#canvasTitle').textContent=designs[design][2];$('#canvasMeta').textContent=design===0||design===1?'242 colours · Hex':'Hex · Select to preview';
if(design===0){let w=document.createElement('div');w.className='wheel';wheelData.forEach(([x,y,r,h])=>{let b=button(h);b.style.left=((x-61)/1358*100)+'%';b.style.top=((y-32)/1556*100)+'%';w.append(b)});c.append(w)}
if(design===1){let w=document.createElement('div');w.className='atlas';[...all].sort((a,b)=>hueOf(a)-hueOf(b)).forEach(h=>w.append(button(h)));c.append(w)}
if(design===2){let w=document.createElement('div');w.className='tones';['Red','Coral','Gold','Lime','Leaf','Jade','Cyan','Azure','Blue','Iris','Violet','Rose'].forEach((name,i)=>{let col=document.createElement('div');col.className='tonecol';col.innerHTML='<label>'+name+'</label>';[94,84,73,62,51,40,29,18,9].forEach(l=>col.append(button(hsl(i*30,74,l))));w.append(col)});c.append(w)}
if(design===3){c.innerHTML='<div class="editor"><div class="sv" tabindex="0" role="slider" aria-label="Saturation and brightness" aria-valuemin="0" aria-valuemax="100" aria-valuenow="80"><i class="cross" style="left:75%;top:20%"></i></div><div class="hues"></div><p>Hue → &nbsp; · &nbsp; Drag in the field for shade · Arrow keys adjust the field</p><div class="recent"></div></div>';let sv=$('.sv');sv.style.setProperty('--hue',hue);let sat,val;[hue,sat,val]=hsv(colour);syncField=()=>{[hue,sat,val]=hsv(colour);sv.style.setProperty('--hue',hue);$('.cross').style.left=sat*100+'%';$('.cross').style.top=(1-val)*100+'%';sv.setAttribute('aria-valuenow',Math.round(sat*100));$('.recent').innerHTML='';[94,82,70,58,46,34,22,10].forEach(l=>$('.recent').append(button(hsl(hue,70,l))))};function update(){let l=val*(1-sat/2),s=l===0||l===1?0:(val-l)/Math.min(l,1-l);choose(hsl(hue,s*100,l*100));$('.cross').style.left=sat*100+'%';$('.cross').style.top=(1-val)*100+'%';sv.setAttribute('aria-valuenow',Math.round(sat*100))}function point(e){let r=sv.getBoundingClientRect();sat=Math.max(0,Math.min(1,(e.clientX-r.left)/r.width));val=1-Math.max(0,Math.min(1,(e.clientY-r.top)/r.height));update()}sv.onpointerdown=e=>{sv.setPointerCapture(e.pointerId);point(e)};sv.onpointermove=e=>{if(e.buttons)point(e)};sv.onkeydown=e=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))return;e.preventDefault();sat=Math.max(0,Math.min(1,sat+(e.key==='ArrowRight'?.02:e.key==='ArrowLeft'?-.02:0)));val=Math.max(0,Math.min(1,val+(e.key==='ArrowUp'?.02:e.key==='ArrowDown'?-.02:0)));update()};for(let i=0;i<24;i++){let b=button(hsl(i*15,100,50));b.onclick=()=>{hue=i*15;sv.style.setProperty('--hue',hue);update()};$('.hues').append(b)}[94,82,70,58,46,34,22,10].forEach(l=>$('.recent').append(button(hsl(hue,70,l))))}
if(design===4){let w=document.createElement('div');w.className='families';['Reds & Corals','Golds & Ochres','Greens & Olives','Cyans & Teals','Blues & Indigos','Violets & Roses'].forEach((name,i)=>{let f=document.createElement('section');f.className='family';f.innerHTML='<h3>'+name+'</h3><div></div>';for(let row=0;row<5;row++)for(let col=0;col<5;col++)f.lastChild.append(button(hsl(i*60+col*10,75-row*5,84-row*14)));w.append(f)});c.append(w)}
$('#neutrals').innerHTML='';for(let i=0;i<12;i++)$('#neutrals').append(button(hsl(0,0,i*100/11)));document.querySelectorAll('#designs button').forEach((b,i)=>b.classList.toggle('active',i===design));document.querySelectorAll('[data-theme]').forEach(b=>b.classList.toggle('active',b.dataset.theme===theme));choose(colour);context()}
designs.forEach((d,i)=>{let b=document.createElement('button');b.textContent=(i+1)+' '+d[0];b.onclick=()=>{design=i;route()};$('#designs').append(b)});document.querySelectorAll('[data-theme]').forEach(b=>b.onclick=()=>{theme=b.dataset.theme;route()});function route(){location.hash=`design-${design+1}-${theme}`}function readRoute(){let m=location.hash.match(/design-([1-5])-(light|dark)/);if(m){design=+m[1]-1;theme=m[2]}document.body.classList.toggle('dark',theme==='dark');render()};window.onhashchange=readRoute;
$('#hex').oninput=()=>{let v=$('#hex').value.trim();if(!v.startsWith('#'))v='#'+v;if(/^#[\da-f]{6}$/i.test(v))choose(v);else $('#error').textContent='Enter a six-digit hex colour.'};$('#apply').onclick=()=>{if($('#error').textContent)return;settings[selected].value=colour;saved[selected]=colour;localStorage.setItem('colorgain-picker-studies',JSON.stringify(saved));sidebar();context();$('#status').textContent='Saved in prototype · '+settings[selected].group+' · '+settings[selected].name};$('#reset').onclick=()=>choose(settings[selected].default);function close(){$('.picker').hidden=true;$('.closed').hidden=false}$('#cancel').onclick=close;$('#close').onclick=close;$('#reopen').onclick=()=>{$('.picker').hidden=false;$('.closed').hidden=true};window.onkeydown=e=>{if(e.key==='Escape')close()};sidebar();readRoute();
